import { notePathFromSlug, projectPathFromSlug } from './paths.js';

export type SlugRedirect = {
  source: string;
  destination: string;
  status: 308;
};

export type Sluggable = {
  slug: string;
  previousSlugs: string[];
  label?: string;
};

/**
 * Derive permanent slug redirects for Notes and Projects.
 * Historical sources always point directly at the current location (no chains).
 * Collision validation fails loudly.
 */
export function deriveSlugRedirects(input: {
  notes: Sluggable[];
  projects: Sluggable[];
}): SlugRedirect[] {
  const redirects: SlugRedirect[] = [];

  collectCollectionRedirects(redirects, input.notes, notePathFromSlug, 'note');
  collectCollectionRedirects(redirects, input.projects, projectPathFromSlug, 'project');

  assertUniqueSources(redirects);
  return sortRedirects(redirects);
}

export function toAstroRedirectMap(
  redirects: SlugRedirect[]
): Record<string, { status: 308; destination: string }> {
  const map: Record<string, { status: 308; destination: string }> = {};
  for (const redirect of redirects) {
    map[redirect.source] = {
      status: redirect.status,
      destination: redirect.destination,
    };
  }
  return map;
}

/** Deterministic generated module source for astro.config.mjs. */
export function renderSlugRedirectModule(
  redirects: SlugRedirect[] = []
): string {
  const map = toAstroRedirectMap(redirects);
  const body = JSON.stringify(map, null, 2);
  return [
    '/**',
    ' * AUTO-GENERATED by scripts/generate-slug-redirects.ts',
    ' * Do not edit by hand. Re-run: npm run generate:redirects',
    ' */',
    `export const slugRedirects = ${body};`,
    '',
  ].join('\n');
}

function collectCollectionRedirects(
  redirects: SlugRedirect[],
  items: Sluggable[],
  pathFor: (slug: string) => string,
  kind: 'note' | 'project'
): void {
  const currentPaths = new Map<string, string>();
  for (const item of items) {
    const destination = pathFor(item.slug);
    if (currentPaths.has(destination)) {
      throw new Error(`Duplicate ${kind} current path: ${destination}`);
    }
    currentPaths.set(destination, item.label ?? item.slug);
  }

  for (const item of items) {
    const destination = pathFor(item.slug);
    const seenPrevious = new Set<string>();

    for (const previous of item.previousSlugs) {
      if (previous === item.slug) {
        throw new Error(
          `${item.label ?? item.slug}: previousSlugs must not include current slug "${previous}" (self-redirect)`
        );
      }
      if (seenPrevious.has(previous)) {
        throw new Error(
          `${item.label ?? item.slug}: duplicate previousSlugs entry "${previous}"`
        );
      }
      seenPrevious.add(previous);

      const source = pathFor(previous);
      if (source === destination) {
        throw new Error(`${item.label ?? item.slug}: self-redirect ${source} → ${destination}`);
      }
      if (currentPaths.has(source)) {
        throw new Error(
          `Historical ${kind} path ${source} collides with current slug of ${currentPaths.get(source)}`
        );
      }

      redirects.push({
        source,
        destination,
        status: 308,
      });
    }
  }
}

function assertUniqueSources(redirects: SlugRedirect[]): void {
  const bySource = new Map<string, string>();
  for (const redirect of redirects) {
    const existing = bySource.get(redirect.source);
    if (existing && existing !== redirect.destination) {
      throw new Error(
        `Ambiguous redirect for ${redirect.source}: ${existing} vs ${redirect.destination}`
      );
    }
    if (existing && existing === redirect.destination) {
      throw new Error(`Duplicate redirect source ${redirect.source} → ${redirect.destination}`);
    }
    bySource.set(redirect.source, redirect.destination);
  }
}

function sortRedirects(redirects: SlugRedirect[]): SlugRedirect[] {
  return [...redirects].sort((a, b) => a.source.localeCompare(b.source));
}
